### ISSUE TITLE
when I run the make command this error is being showed

### ISSUE THREAD

**Issue by SaptakBhoumik** [koreaneggroll/C-plus-minus#3]
![image](https://user-images.githubusercontent.com/74509281/115706760-9f1a1380-a38b-11eb-984e-fb92dac672d5.png)
Can you tell me how to solve this issue. Thanks in advance

**Comment by Arin-Grigoras** [comment]
you're on windows i am making this on linux

**Comment by Arin-Grigoras** [comment]
this is not to solve the issue but try to run only gcc without anything else. Like just type `gcc` into the terminal and see what happens

**Comment by Arin-Grigoras** [comment]
if it tells you an error you don't have gcc

**Comment by Arin-Grigoras** [comment]
try to get wsl working if you want to contribute. There are a lot of tutorials on the internet

**Comment by Arin-Grigoras** [comment]
srry for the incovinience

**Comment by SaptakBhoumik** [comment]
Ok I will try again after setting up wsl

**Comment by SaptakBhoumik** [comment]
> if it tells you an error you don't have gcc



I have gcc

**Comment by SaptakBhoumik** [comment]
@koreaneggroll 
![image](https://user-images.githubusercontent.com/74509281/115737698-fd55ef00-a3a9-11eb-82f0-5d9fd25b3514.png)
After I set up wsl it was able to execute the make command but after that, I ran the next command but it failed to execute it

**Comment by Arin-Grigoras** [comment]
yeah i forgot to update the readme. Try running `./cpm compile ./testing/main.cpm ./testing/main.o

**Comment by SaptakBhoumik** [comment]
Syntax error: no such instruction '' at line: 1
This is what I get

**Comment by Arin-Grigoras** [comment]
hmmm

**Comment by Arin-Grigoras** [comment]
what does the cpm file look like ?

**Comment by SaptakBhoumik** [comment]
> what does the cpm file look like ?

push #1
push #0
add
ext

**Comment by Arin-Grigoras** [comment]
check if there any whitespace that shouldn't be there

**Comment by SaptakBhoumik** [comment]
![image](https://user-images.githubusercontent.com/74509281/115739770-d3053100-a3ab-11eb-854c-6bea79dde02e.png)

**Comment by Arin-Grigoras** [comment]
hmm thats weird

**Comment by SaptakBhoumik** [comment]
How will I fix it then

**Comment by Arin-Grigoras** [comment]
i have no idea for me it works

**Comment by SaptakBhoumik** [comment]
Hmm
